- hosts: controller
  become: true
  tasks:
  - name: restart chrony
    service: name=chrony state=restarted

- hosts: network, compute
  become: true
  tasks:
  - name: restart chrony
    service: name=chrony state=restarted

# We don't restart chrony on block node because in our installation Cinder service is
# provided by controller node and it is already restarted
#- hosts: block
#  become: true
#  tasks:
#    - name: restart chrony
#      service: name=chrony state=restarted

- hosts: controller
  become: true
  tasks:
  - name: restart rabbitmq
    service: name=rabbitmq-server state=restarted
  - name: restart mysql
    service: name=mysql state=restarted
  - name: restart memcached
    service: name=memcached state=restarted
  - name: restart apache
    service: name=apache2 state=restarted
  - name: restart glance-registry
    service: name=glance-registry state=restarted
  - name: restart glance-api
    service: name=glance-api state=restarted
  - name: restart nova-api
    service: name=nova-api state=restarted
  - name: restart nova-consoleauth
    service: name=nova-consoleauth state=restarted
  - name: restart nova-scheduler
    service: name=nova-scheduler state=restarted
  - name: restart nova-conductor
    service: name=nova-conductor state=restarted
  - name: restart nova-novncproxy
    service: name=nova-novncproxy state=restarted

- hosts: compute
  become: true
  tasks:
  - name: restart nova-compute
    service: name=nova-compute state=restarted

- hosts: controller
  become: true
  tasks:
  - name: restart neutron-server
    service: name=neutron-server state=restarted

- hosts: network
  become: true
  tasks:
  - name: Restart openvswitch-switch service
    service: name=openvswitch-switch state=restarted
#  - name: restart ovs-cleanup
#    service: name=neutron-ovs-cleanup state=restarted
  - name: restart neutron-openvswitch-agent
    service: name=neutron-openvswitch-agent state=restarted
  - name: restart neutron-dhcp-agent
    service: name=neutron-dhcp-agent state=restarted
  - name: restart neutron-metadata-agent
    service: name=neutron-metadata-agent state=restarted
  - name: restart neutron-l3-agent
    service: name=neutron-l3-agent state=restarted


- hosts: compute
  become: true
  tasks:
#  - name: restart ovs-cleanup     
#    service: name=neutron-ovs-cleanup state=restarted
  - name: restart neutron-openvswitch-agent
    service: name=neutron-openvswitch-agent state=restarted
  
- hosts: controller
  become: true
  tasks:
  - name: restart cinder-scheduler
    service: name=cinder-scheduler state=restarted
  - name: restart tgt
    service: name=tgt state=restarted
  - name: restart cinder-volume
    service: name=cinder-volume state=restarted

